---
- name: VM Snapshot Manager
  hosts: localhost
  gather_facts: yes
  collections:
    - community.vmware
    - awx.awx
    - community.general
  vars:
    vcenters:
      - vcenter1.example.com
      - vcenter2.example.com
    vcenter_username: "{{ lookup('env', 'VCENTER_USER') }}"  # Veya extra vars ile tanımlayın
    vcenter_password: "{{ lookup('env', 'VCENTER_PASS') }}"  # Veya extra vars ile tanımlayın
    datacenter: "{{ domain }}"  # Survey'den
    job_template_name: "VM Snapshot Manager"  # Bu template'in adı
    awx_host: "https://awx.example.com"  # AWX URL
    awx_username: "{{ lookup('env', 'AWX_USER') }}"  # Veya extra vars
    awx_password: "{{ lookup('env', 'AWX_PASS') }}"  # Veya extra vars
    smtp_host: "smtp.example.com"
    smtp_port: 25
    smtp_from: "awx@example.com"

  tasks:
    - name: Sunucu listesini ayır
      set_fact:
        servers: "{{ servers_str.split(',') | map('trim') | list }}"

    - name: 10'dan fazla sunucu kontrolü (take için)
      when: action == 'take' and servers | length > 10
      block:
        - name: Çok fazla sunucu için email gönder
          community.general.mail:
            host: "{{ smtp_host }}"
            port: "{{ smtp_port }}"
            from: "{{ smtp_from }}"
            to: "{{ user_email }}"
            subject: "Hata: Çok fazla sunucu"
            body: "10'dan fazla sunucu işlenemez."
        - fail:
            msg: "Çok fazla sunucu"

    - name: Listeleri başlat
      set_fact:
        snapped_servers: []
        not_found_servers: []
        error_servers: []

    - name: Take için snapshot adı üret
      set_fact:
        snapshot_name: "auto_snapshot_{{ ansible_date_time.iso8601_basic_short }}"
      when: action == 'take'

    - name: Her sunucuyu işle
      loop: "{{ servers }}"
      loop_control:
        loop_var: server
      block:
        - name: vCenter'larda VM ara
          community.vmware.vmware_guest_find:
            hostname: "{{ item }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            validate_certs: no
            name: "{{ server }}"
            datacenter: "{{ datacenter }}"
          register: find_result
          loop: "{{ vcenters }}"
          ignore_errors: yes

        - name: Bulunan vCenter'ları belirle
          set_fact:
            found_vcenters: "{{ find_result.results | selectattr('failed', 'equalto', false) | selectattr('folders', 'length', 'gt', 0) | map(attribute='hostname') | list }}"

        - name: Bulunamadıysa ekle
          set_fact:
            not_found_servers: "{{ not_found_servers + [server] }}"
          when: found_vcenters | length == 0

        - name: Bulunduysa işle
          when: found_vcenters | length > 0
          block:
            - name: İlk bulunan vCenter ve folder'ı set et
              set_fact:
                vm_vcenter: "{{ found_vcenters[0] }}"
                vm_folder: "{{ find_result.results | selectattr('hostname', 'equalto', found_vcenters[0]) | first.folders | first }}"

            - name: Snapshot bilgisini al
              community.vmware.vmware_guest_snapshot_info:
                hostname: "{{ vm_vcenter }}"
                username: "{{ vcenter_username }}"
                password: "{{ vcenter_password }}"
                validate_certs: no
                folder: "{{ vm_folder }}"
                name: "{{ server }}"
                datacenter: "{{ datacenter }}"
              register: snap_info

            - name: Take için snapshot sayısı kontrolü
              when: action == 'take' and (snap_info.current_snapshots | default([]) | length) >= 5
              block:
                - set_fact:
                    error_servers: "{{ error_servers + [server + ': çok fazla snapshot'] }}"
                - name: Çok fazla snapshot için email gönder
                  community.general.mail:
                    host: "{{ smtp_host }}"
                    port: "{{ smtp_port }}"
                    from: "{{ smtp_from }}"
                    to: "{{ user_email }}"
                    subject: "Hata: {{ server }} için çok fazla snapshot"
                    body: "{{ server }} sunucusunda 5 veya daha fazla snapshot var."

            - name: Snapshot al veya sil
              community.vmware.vmware_guest_snapshot:
                hostname: "{{ vm_vcenter }}"
                username: "{{ vcenter_username }}"
                password: "{{ vcenter_password }}"
                validate_certs: no
                folder: "{{ vm_folder }}"
                name: "{{ server }}"
                datacenter: "{{ datacenter }}"
                state: "{{ 'present' if action == 'take' else 'remove' }}"
                snapshot_name: "{{ snapshot_name }}"
                description: "Otomatik snapshot"
              when: action == 'delete' or (action == 'take' and (snap_info.current_snapshots | default([]) | length) < 5)
              register: snap_result

            - name: Başarılıysa snapped'e ekle
              set_fact:
                snapped_servers: "{{ snapped_servers + [server] }}"
              when: not snap_result.failed

    - name: Sonuç email'i gönder
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        from: "{{ smtp_from }}"
        to: "{{ user_email }}"
        subject: "Snapshot işlem sonuçları - {{ action }}"
        body: |
          İşlenen sunucular: {{ snapped_servers | join(', ') }}
          Bulunamayanlar: {{ not_found_servers | join(', ') }}
          Hatalar: {{ error_servers | join(', ') }}

    - name: Take için silme schedule'ı oluştur
      when: action == 'take' and snapped_servers | length > 0
      block:
        - name: Gelecek epoch hesapla
          set_fact:
            now_epoch: "{{ ansible_date_time.epoch | int }}"
            days_seconds: "{{ days | int * 86400 }}"
            future_epoch: "{{ now_epoch + days_seconds }}"

        - name: Gelecek tarih hesapla
          set_fact:
            future_date: "{{ future_epoch | strftime('%Y%m%dT%H%M%SZ') }}"

        - name: Schedule oluştur
          awx.awx.schedule:
            name: "Sil {{ snapshot_name }} için {{ snapped_servers | join('_') }}"
            unified_job_template: "{{ job_template_name }}"
            rrule: "DTSTART:{{ future_date }} RRULE:FREQ=MINUTELY;INTERVAL=1;COUNT=1"
            extra_data:
              action: "delete"
              servers_str: "{{ snapped_servers | join(',') }}"
              domain: "{{ domain }}"
              user_email: "{{ user_email }}"
              snapshot_name: "{{ snapshot_name }}"
            state: present
            controller_host: "{{ awx_host }}"
            controller_username: "{{ awx_username }}"
            controller_password: "{{ awx_password }}"
            validate_certs: no